### ISSUE TITLE
light blue line

### ISSUE THREAD

**Issue by akarlinsky** [johnmackintosh/cusumcharter#9]
Thanks for a great package!
This might be a silly question, but I'm not sure what the bright-blue (as opposed to dark-blue) line represents and how to interpret it?
![image](https://github.com/johnmackintosh/cusumcharter/assets/48435065/e38d96c3-5479-4e5c-aeaa-b34970258fd0)

**Comment by johnmackintosh** [comment]
Hi - the light blue line represents the  negative cusum statistic.

(I thought I'd mentioned this in the documentation, but, on review, I have not).

The line and point colours can be changed using the function arguments `pos_col` and `neg_col`

**Comment by akarlinsky** [comment]
Thanks! and how to interpret the negative vs positive cusum statstic? 
Tried to look around a little and didn't find something very clear on this.

**Comment by johnmackintosh** [comment]
Each point is compared to the target. This will result in either a positive or negative variance from the target value.
These lines are the cumulative sum of those variances.

The shaded area represents the control limits. The advantage of plotting the lines is it allows you to see the exact points where the process begins to go out of control, and to more easily visualise the variance within the entire process.. the lines will be closer together if the process is more stable

**Comment by akarlinsky** [comment]
Thanks! 
You can close the issue if you want or keep it until you put this into the documentation :)
